apiVersion: v1
kind: PersistentVolume
metadata:
  name: docker-volumes-media-intree-nfs-pv
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  nfs:
    server: 192.168.50.108
    path: /volume1/docker-volumes-media
  persistentVolumeReclaimPolicy: Retain
