apiVersion: v1
kind: PersistentVolume
metadata:
  name: homes-intree-nfs-pv
spec:
  capacity:
    storage: 250Gi
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  nfs:
    server: 192.168.50.108
    path: /volume1/homes
  persistentVolumeReclaimPolicy: Retain
