apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docker-volumes-media-intree-nfs-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
  volumeName: docker-volumes-media-intree-nfs-pv
  storageClassName: ""
