apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homes-intree-nfs-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 250Gi
  volumeName: homes-intree-nfs-pv
  storageClassName: ""
