apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-config-local-path-pvc
  namespace: default
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 25Gi   # metadata/thumbnails/etc add up, give it room
