# default pool - dynamic IPs for most services
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default-pool
  namespace: metallb-system
spec:
  addresses:
    - 192.168.1.120-192.168.1.127
    - 192.168.1.129-192.168.1.200
---
# stable pool - reserved for gateway/ingress
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: gateway-pool
  namespace: metallb-system
spec:
  addresses:
    - 192.168.1.128/32
