apiVersion: v1
kind: Service
metadata:
  name: my-postgresql-cluster-lb
spec:
  type: LoadBalancer
  selector:
    cnpg.io/cluster: my-postgresql-cluster
    role: primary
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
